server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: savepdf-service
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        generate_statistics: false
#    generate-ddl: true
    show-sql: false
    hibernate:
      use-new-id-generator-mappings: false

  datasource:
    url: jdbc:mariadb://localhost:3306/pocpdf
    username: ${MARIA_DB_USER:root}
    #password: ${MARIA_DB_PASSWORD:toor}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      max-lifetime: 600000
      maximum-pool-size: 20
      auto-commit: true
      connection-timeout: 10000
      minimum-idle: 5
      idle-timeout: 300000

   
logging:
  level:
    org.apache: INFO
    org.springframework.security: INFO 
    com.thincode: INFO
    spring.jpa: INFO